enableProfiler: false
localPort: 8888
routes:
    "/Users/index": "/"
    "/Users/signin": "/signin"
    "/Users/register": "/register"
    "/Users/process_registration": "/process/register"
    "/Users/process_signin": "/process/signin"
    "/Users/success": "/success"
    "/Users/logoff": "/logoff"
dbdriver: "mysql"
database1:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "postgres"
    max: 30
database2:
    host: "localhost"
    port: 3308
    user: "root"
    password: ""
    database: "gemu_mvc"
    waitForConnections: true
    connectionLimit: 10
    queueLimit: 0
database3:
    uri: "mongodb+srv://markad:rL64xwvroAYU25fV@gemu-mvc.0rdsfx8.mongodb.net/?retryWrites=true&w=majority"
    database: "gemu-mvc"
enableRedis: true
sessionConfig:
    secret: "gemu_mvc"
    resave: false
    saveUninitialized: true
    cookie:
        secure: false
